# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: projectbackenddevelopment
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
      - 5001:5000